/**
 * Code to specify the authentication method used, as published separately in an external authentication method code set.
 * ISO20022 External Code
 * Original name: ExternalAuthenticationMethod1Code
 */
export enum AuthenticationMethod {
  /** Serial Number of the acceptor's certificate. */
  ACSN = "ACSN",
  /** Cardholder billing address. */
  ADDB = "ADDB",
  /** Shipping address. */
  ADDS = "ADDS",
  /** Account-based digital signature authentication. */
  APKI = "APKI",
  /** Number assigned by a government agency to identify foreign nationals. */
  ARNB = "ARNB",
  /** Response Card Cryptogram (ARPC) verification. */
  ARPC = "ARPC",
  /** Verification of a cryptogram generated by a chip card, for instance an ARQC (Authorisation Request Cryptogram). */
  ARQC = "ARQC",
  /** Application Transaction Counter. */
  ATCC = "ATCC",
  /** A value is used to verify an already performed authentication, used for non ThreeDS related authentication. */
  AUVA = "AUVA",
  /** Biometric authentication of the cardholder. */
  BIOM = "BIOM",
  /** Date of birth of a person. */
  BTHD = "BTHD",
  /** Consumer Device Cardholder Verification Method. */
  CDCM = "CDCM",
  /** Cardholder data provided for verification. */
  CDHI = "CDHI",
  /** Name of cardholder. */
  CHDN = "CHDN",
  /** Cardholder address. */
  CHSA = "CHSA",
  /** Serial Number of the cardholder's certificate. */
  CHSN = "CHSN",
  /** Registration number of a company. */
  CPNY = "CPNY",
  /** Electronic signature capture (handwritten signature). */
  CPSG = "CPSG",
  /** Verification of Card Security Code. */
  CSCV = "CSCV",
  /** Authentication performed during a secure electronic commerce transaction. */
  CSEC = "CSEC",
  /** Customer number used as a mechanism of authentication. */
  CUID = "CUID",
  /** Number assigned by a driving license authority to a person. */
  DRID = "DRID",
  /** Identification of a driver in a fleet of vehicles. */
  DRVI = "DRVI",
  /** Electronic mail address. */
  EMAL = "EMAL",
  /** Number assigned to an employee by an employer. */
  EMIN = "EMIN",
  /** Number assigned to an employer by a registration authority. */
  EMRN = "EMRN",
  /** Biographics authentication in an offline mode. */
  FBIG = "FBIG",
  /** Biometrics authentication in an offline mode. */
  FBIO = "FBIO",
  /** PIN generated offline and transmitted in clear */
  FCPN = "FCPN",
  /** Off-line PIN authentication (Personal Identification Number). */
  FPIN = "FPIN",
  /** Number assigned by a national authority to an identity card. */
  IDCN = "IDCN",
  /** Identification of law enforcement. */
  LAWE = "LAWE",
  /** Manual verification, for example passport or drivers license. */
  MANU = "MANU",
  /** Identification of military. */
  MILI = "MILI",
  /** Customer mobile phone number. */
  MOBL = "MOBL",
  /** Biographics authentication in an online mode. */
  NBIG = "NBIG",
  /** On-line PIN authentication (Personal Identification Number). */
  NPIN = "NPIN",
  /** National Identifier. */
  NTID = "NTID",
  /** Non visible Card Security Code. */
  NVSC = "NVSC",
  /** Other cardholder data provided for identification. */
  OCHI = "OCHI",
  /** PIN generated offline and transmitted encrypted. */
  OFPE = "OFPE",
  /** Authentication of data in an offline mode. */
  OLDA = "OLDA",
  /** Analysis of signature transmitted offline. */
  OLDS = "OLDS",
  /** Other type of verification defined at national level. */
  OTHN = "OTHN",
  /** Other type of verification defined at private level. */
  OTHP = "OTHP",
  /** Verification of a one-time password provided by the issuer. */
  OTPW = "OTPW",
  /** Number assigned by a passport authority to a passport. */
  PASS = "PASS",
  /** Verification based on digits of the postal code. */
  PCDV = "PCDV",
  /** Generical phone number. */
  PHNB = "PHNB",
  /** Customer home phone number. */
  PHOM = "PHOM",
  /** PKI (Public Key Infrastructure) based digital signature. */
  PKIS = "PKIS",
  /** Place of birth of a person. */
  PLOB = "PLOB",
  /** Handwritten paper signature. */
  PPSG = "PPSG",
  /** Proxy. */
  PRXY = "PRXY",
  /** Authentication by a passcode. */
  PSCD = "PSCD",
  /** Authentication based on statistical cardholder behaviour. */
  PSVE = "PSVE",
  /** Authentication by a password. */
  PSWD = "PSWD",
  /** Customer business phone number. */
  PWOR = "PWOR",
  /** Qualified Certificate. */
  QWAC = "QWAC",
  /** Channel-encrypted transaction. */
  SCNL = "SCNL",
  /** Electronic commerce transaction secured with the X.509 certificate of a customer. */
  SCRT = "SCRT",
  /** Shipping address from verification. */
  SHAF = "SHAF",
  /** Shipping address to verification */
  SHAT = "SHAT",
  /** Number assigned by a social security agency. */
  SSYN = "SSYN",
  /** A value used to validate the authorised use of a token. */
  TAVV = "TAVV",
  /** Authentication performed during a secure electronic commerce transaction. */
  THDS = "THDS",
  /** Identification used for travel. */
  TRVL = "TRVL",
  /** Number assigned by a tax authority to an entity. */
  TXID = "TXID",
}